### ISSUE TITLE
reduce duplicated terms

### ISSUE THREAD

**Issue by gnujoow** [many-things/cosmos-query#6]
https://github.com/many-things/cosmos-query/blob/0ed520f12ffc9218d1eb81fe9444c05c0e94d5db/packages/core/src/apis/cosmos/bank/types.ts#L62-L65

https://github.com/many-things/cosmos-query/blob/0ed520f12ffc9218d1eb81fe9444c05c0e94d5db/packages/core/src/apis/cosmos/bank/types.ts#L3-L6

https://github.com/many-things/cosmos-query/blob/0ed520f12ffc9218d1eb81fe9444c05c0e94d5db/packages/core/src/apis/osmosis/incentives/types.ts#L39-L42

https://github.com/many-things/cosmos-query/blob/0ed520f12ffc9218d1eb81fe9444c05c0e94d5db/packages/core/src/apis/osmosis/lockup/types.ts#L1-L4

https://github.com/many-things/cosmos-query/blob/0ed520f12ffc9218d1eb81fe9444c05c0e94d5db/packages/core/src/apis/osmosis/claim/types.ts#L18-L21

these terms are describing the same interface. I suggest reducing the number of terms if they are not neccesary

**Comment by Ryz0nd** [comment]
Good
